### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FemBoxbrawl** [stavsap/comfyui-ollama#16]
[Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
12:55:33.121 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1879, in load_custom_node
12:55:33.121 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
12:55:33.123 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
12:55:33.123 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
12:55:33.124 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-ollama\__init__.py", line 1, in <module>
12:55:33.125 [Warning] ComfyUI-0 on port 7821 stderr:     from .CompfyuiOllama import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
12:55:33.126 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-ollama\CompfyuiOllama.py", line 3, in <module>
12:55:33.126 [Warning] ComfyUI-0 on port 7821 stderr:     from ollama import Client
12:55:33.127 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'ollama'
12:55:33.127 [Warning] ComfyUI-0 on port 7821 stderr:

**Comment by FemBoxbrawl** [comment]
installed extra missing custom nodes
